import {tList} from '../../helper/renderer';
let exp: any[] = [];

exp.push(tList({
    t: "",
    list: [
        { l: "beat - beat - beaten" },
        { l: "become - became - become" },
        { l: "begin - began - begun" },
        { l: "bend - bent - bent" },
        { l: "bite - bit - bitten" },
        { l: "blow - blew - blown" },
        { l: "break - broke - broken" },
        { l: "bring - brought - brought" },
        { l: "build - built - built" },
        { l: "burst - burst - burst" },
        { l: "buy - bought - bought" },
        { l: "catch - caught - caught" },
        { l: "choose - chose - chosen" },
        { l: "come - came - come" },
        { l: "cost - cost - cost" },
        { l: "cut - cut - cut" },
        { l: "dig - dug - dug" },
        { l: "do - did - done" },
        { l: "draw - drew - drawn" },
        { l: "drink - drank - drunk" },
        { l: "drive - drove - driven" },
        { l: "eat - ate - eaten" },
        { l: "fall - fell - fallen" },
        { l: "feed - fed - fed" },
        { l: "feel - felt - felt" },
        { l: "fight - fought - fought" },
        { l: "find - found - found" },
        { l: "fly - flew - flown" },
        { l: "forget - forgot - forgotten" },
        { l: "freeze - froze - frozen" },
        { l: "give - gave - given" },
        { l: "go - went - gone" },
        { l: "grow - grew - grown" },
        { l: "have - had - had" },
        { l: "hear - heard - heard" },
        { l: "hide - hid - hidden" },
        { l: "hit - hit - hit" },
        { l: "hold - held - held" },
        { l: "hurt - hurt - hurt" },
        { l: "keep - kept - kept" },
        { l: "know - knew - known" },
        { l: "lead - led - led" },
        { l: "leave - left - left" },
        { l: "let - let - let " },
        { l: "light - lit - lit " },
        { l: "lose - lost - lost " },
        { l: "make - made - made " },
        { l: "mean - meant - meant " },
        { l: "meet - met - met " },
        { l: "pay - paid - paid " },
        { l: "put - put - put " },
        { l: "read - read - read " },
        { l: "ride - rode - ridden " },
        { l: "ring - rang - rung " },
        { l: "rise - rose - risen " },
        { l: "run - ran - run " },
        { l: "say - said - said " },
        { l: "see - saw - seen " },
        { l: "sell - sold - sold " },
        { l: "send - sent - sent " },
        { l: "shake - shook - shaken " },
        { l: "shine - shone - shone " },
        { l: "shoot - shot - shot " },
        { l: "shut - shut - shut " },
        { l: "sing - sang - sung " },
        { l: "sink - sank - sunk " },
        { l: "sit - sat - sat " },
        { l: "sleep - slept - slept" },
        { l: "speak - spoke - spoken " },
        { l: "spread - spread - spread " },
        { l: "stand - stood - stood " },
        { l: "steal - stole - stolen " },
        { l: "stick - stuck - stuck " },
        { l: "strike - struck - struck " },
        { l: "sweep - swept - swept " },
        { l: "swim - swam - swum " },
        { l: "take - took - taken " },
        { l: "teach - taught - taught " },
        { l: "tear - tore - torn " },
        { l: "tell - told - told " },
        { l: "think - thought - thought" },
        { l: "throw - threw - thrown " },
        { l: "wake - woke - woken " },
        { l: "wear - wore - worn " },
        { l: "win - won - won " },
        { l: "write - wrote - written" }
    ]
}));

export = {
    exp: exp
};
