/// <reference path="../../typings/tsd.d.ts" />
export =  {
    ROOT_ITEM_CLICK: 'ROOT_ITEM_CLICK',
    SWITCH_ACTION: 'SWITCH_ACTION',
    MAXIMALIZE_SETTINGS: 'MAXIMALIZE_SETTINGS',
    CHOOSE_PICTURE : 'CHOOSE_PICTURE',
    BOARD_NEXT: 'BOARD_NEXT',
    BOARD_PREV: 'BOARD_PREV'
}
