/// <reference path="../../typings/tsd.d.ts" />
export =  {
    LOGIN : 'LOGIN',
    REGISTER : 'REGISTER',
    GREETINGS_SHOW_LESSONS: 'GREETINGS_SHOW_LESSONS',
    ROOT_ITEM_CLICK: 'ROOT_ITEM_CLICK',
    SWITCH_ACTION: 'SWITCH_ACTION',
    MAXIMALIZE_SETTINGS: 'MAXIMALIZE_SETTINGS',
    CHOOSE_PICTURE: 'CHOOSE_PICTURE',
    CHOOSE_RADIO: 'CHOOSE_RADIO',
    CHOOSE_ONE_TWO_THREE: 'CHOOSE_ONE_TWO_THREE',
    BOARD_NEXT: 'BOARD_NEXT',
    BOARD_PREV: 'BOARD_PREV',
    BOARD_NEXT_RANDOM : 'BOARD_NEXT_RANDOM',
    READ: 'READ',
    SUBSCRIBE: 'SUBSCRIBE',
    GREETINGS_CONTINUE: 'GREETINGS_CONTINUE',
    EXPLENATION_SCROLL_TOP : 'EXPLENATION_SCROLL_TOP',
    EXPLENATION_SCROLL_MIDDLE : 'EXPLENATION_SCROLL_MIDDLE',
    EXPLENATION_SCROLL_RESET : 'EXPLENATION_SCROLL_RESET'
}
