/// <reference path='../../../../typings/tsd.d.ts' />
const b = '<br>';

const html = '<div>'
    + b + 'Present'
    + b + ''
    + b + 'I <u>am</u>'
    + b + 'you <u>are</u>'
    + b + 'he/she/it <u>is</u>'
    + b + 'we <u>are</u>'
    + b + 'you <u>are</u>'
    + b + 'they <u>are</u>'
    + b + ''
    + b + 'Past'
    + b + ''
    + b + 'I <u>was</u>'
    + b + 'you <u>were</u>'
    + b + 'he/she/it <u>was</u>'
    + b + 'we <u>were</u>'
    + b + 'you <u>were</u>'
    + b + 'they <u>were</u>'
    + b + ''
    + b + 'Negation'
    + b + ''
    + b + 'I am <u>not</u>'
    + b + 'he was <u>not</u>'
    + b + 'we are <u>not</u>'
    + b + 'they were <u>not</u>'
    + b + ''
    + b + 'Questions'
    + b + ''
    + b + '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; They <u>are</u> tired.'
    + b + '<u>Are</u> they &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tired?'
    + b + ''
    + b + 'Answers'
    + b + ''
    + b + 'Are you tired?'
    + b + '-Yes.'
    + b + '-Yes, I am tired.'
    + b + ''
    + b + 'Are you hungry?'
    + b + '-Yes.'
    + b + '-Yes, I am hungry.'
    + b + ''
    + b + 'Are you sleepy?'
    + b + '-No.'
    + b + '-No, I am not sleepy.'
    + b + ''
    + b + ''
    + b + '</div>'

export = {
    html: html
};
  